# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['Crazy_Bird.py'],
             pathex=['C:\\Users\\phr20gg\\Documents\\GitHub\\MLTT_pygame_new_v2\\Exp_5_MasterAyesha'],
             binaries=[],
             datas=[('pics\\sampleBird_scaled_state1.png', 'pics\\'), 
('pics\\sampleBird_scaled_state2.png', 'pics\\'), 
('pics\\sampleBird_scaled_state3.png', 'pics\\'), 
('pics\\sampleStar.png', 'pics\\'), 
('pics\\sampleObstacle_scaled.png', 'pics\\'),
('pics\\sampleGate_scaled.png', 'pics\\'),
('pics\\Instruct_1.png', 'pics\\'),
('pics\\Instruct_2.png', 'pics\\'),
('pics\\Instruct_3.png', 'pics\\'),
('pics\\Instruct_4.png', 'pics\\'),
('pics\\Instruct_5.png', 'pics\\'),
('pics\\Instruct_6.png', 'pics\\'),
('pics\\Training_1.png', 'pics\\'),
('pics\\Training_2.png', 'pics\\'),
('pics\\Training_3.png', 'pics\\'),
('pics\\Training_4.png', 'pics\\'),
('files\\Exp_Conditions_Infrequent.csv', 'files\\'),
('files\\Exp_Conditions_Frequent.csv', 'files\\'),
('files\\Instruktion_1.txt', 'files\\'),
('files\\Instruktion_2.txt', 'files\\'),
('files\\Instruktion_3.txt', 'files\\'),
('files\\Instruktion_4.txt', 'files\\'),
('files\\Instruktion_5.txt', 'files\\'),
('files\\Instruktion_6.txt', 'files\\'),
('files\\Instruktion_7.txt', 'files\\'),
('files\\Instruktion_8.txt', 'files\\'),
('pics\\InformierteEinwilligung_short_1.ppm', 'pics\\'),
('pics\\InformierteEinwilligung_short_2.ppm', 'pics\\'),
('pics\\InformierteEinwilligung_short_3.ppm', 'pics\\')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Crazy_Bird',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
